# add your settings here (overriding the defaults)
# https://biocypher.org/installation.html#biocypher-settings

biocypher:
  offline: true
  debug: false
  schema_config_path: config/schema_config.yaml
  cache_directory: .cache
  ## head ontology MIAPPE/PPEO configuration
#  head_ontology:
#    url: ./ontologies/miappebiocypher.owl.ttl
#    root_node: entity
#  tail_ontologies:
#    ppeo:
#      merge_nodes: false
#      url: https://raw.githubusercontent.com/MIAPPE/MIAPPE-ontology/refs/heads/master/PPEO.owl
#      head_join_node: biological concept
#      tail_join_node: study
  # Head ontlogy BioLink configuration
  head_ontology:
    url: https://raw.githubusercontent.com/biolink/biolink-model/refs/heads/master/project/owl/biolink_model.owl.ttl
    root_node: entity

neo4j:
  delimiter: '\t'
  quote_character: "\""
  array_delimiter: "|"
  skip_duplicate_nodes: true
  skip_bad_relationships: true


