# add your desired knowledge graph components here

trial:
    is_a: dataset
    represented_as: node
    preferred_id: trialDbId
    input_label: trialName


study:
    is_a: dataset
    represented_as: node
    preferred_id: studyDbId
    input_label: studyName
    properties:
        germplasmDbIds: string[]

germplasm:
    is_a: plant
    represented_as: node
    preferred_id: germplasmDbId
    input_label: germplasmName

trial study list:
    is_a: information content entity
    represented_as: edge
    input_label: trial_studies

study germplasm list:
    is_a: information content entity
    represented_as: edge
    input_label: studies_germplasm
