# add your desired knowledge graph components here

trial:
    is_a: dataset
    represented_as: node
    preferred_id: trialDbId
    input_label: trial
    properties:
        trialName: string
        trialDbId: string
        documentationURL: string



study:
    #is_a: dataset
    represented_as: node
    preferred_id: studyDbId
    input_label: study
    properties:
        germplasmDbIds: string[]
        documentationURL: string
        locationDbId: string
        locationName: string
        observationVariableDbIds: string[]
        studyName: string
        studyDbId: string
        studyType: string
        seasons: string[]
        trialName: string
        startDate: string
        endDate: string

germplasm:
    is_a: plant
    represented_as: node
    preferred_id: germplasmDbId
    input_label: germplasm
    properties:
        germplasmDbId: string
        germplasmPUI: string
        germplasmName: string
        accessionNumber: string
        commonCropName: string
        countryOfOriginCode: string
        genus: string
        species: string
        subtaxa: string
        #synonyms: string[]
        pedigree: string
        genusSpecies: string
        instituteCode: string
        instituteName: string
        biologicalStatusOfAccessionCode: string
        biologicalStatusOfAccessionDescription: string
        presenceStatus: string
        taxonCommonNames: string[]


trial study list:
    is_a: entity
    represented_as: edge
    input_label: trial_studies
    source: trial
    target: study

study germplasm list:
    is_a: entity
    represented_as: edge
    input_label: studies_germplasm
    source: study
    target: germplasm
